### ISSUE TITLE
Conflict with 5dim_battlefield and Cargo ships but only with Krastorio 2 enabled.

### ISSUE THREAD

**Issue by Glendening** [McGuten/Factorio5DimMods#10]
Weird one.
Error while running setup for entity prototype "or_radar" (radar): next_upgrade target (5d-radar-02) must have the same bounding box.
5dim_battlefield 1.1.0 and cargo-ships 0.0.57 and  Krastorio2 1.0.13
disable any 1 of the three from this combo and everything loads fine.

**Comment by McGuten** [comment]
Thanks you for the report!

Add compatibility with cargo ships and krastorio in the core 1.1.4!
