### ISSUE TITLE
[Nuclear] Missing uranium processing

### ISSUE THREAD

**Issue by H4ckerxx44** [McGuten/Factorio5DimMods#100]
Vanilla centrifuge:
![grafik](https://github.com/user-attachments/assets/e651836e-efee-421b-b482-fb49252243e2)

MK10 centrifuge:
![grafik](https://github.com/user-attachments/assets/6d116275-303d-4f07-8daf-53bcdeb58769)

**Comment by McGuten** [comment]
![image](https://github.com/user-attachments/assets/589d0ff1-40bf-46a1-8f37-27f78d15a0c0)
i can see the recipe, what mods are you using?

**Comment by H4ckerxx44** [comment]
Lots of mods, I guess thats a mod conflict then.

**Comment by H4ckerxx44** [comment]
I have removed [Gleba Reborn](https://mods.factorio.com/mod/gleba-reborn?) from my game and now recipes show up again, make of that what you want :D
