### ISSUE TITLE
Turbo belt tier

### ISSUE THREAD

**Issue by kryojenik** [McGuten/Factorio5DimMods#103]
You have the turbo belt tier hanging out all by itself.  Since it is the same at MK 4 Transports, but more expensive and harder to make, they'll likely be ignored.  That is probably why you didn't bother with the Turbo Loaders.  They should be removed or hidden.

**Comment by McGuten** [comment]
it will bi fixed when i start to update space mod compatibility, for now the mod its just ported to 2.0
