### ISSUE TITLE
Bulk inserters name is screwed up

### ISSUE THREAD

**Issue by zgrillo2004** [McGuten/Factorio5DimMods#108]
Hi. I am using all of the 5Dim mods and Bob's inserters mod in my game and for some reason the bulk inserters aren't showing what they should be showing. Instead, the description is that it is an "Unknown key" which may indicate a locale problem since I'm an English speaker.. it affects all of the bulk inserters only. Here is a sample image of my problem
![inserter_bug](https://github.com/user-attachments/assets/4f454584-b2ba-40aa-bee4-056f2dd9f822)

**Comment by zgrillo2004** [comment]
Just made a little bugfix for myself but I dont know how to contribute it.
I made a new line after 248
so now in line 250 to 258 I made this code as follows

```
5d-bulk-inserter-02=Bulk Inserter MK2
5d-bulk-inserter-03=Bulk Inserter MK3
5d-bulk-inserter-04=Bulk Inserter MK4
5d-bulk-inserter-05=Bulk Inserter MK5
5d-bulk-inserter-06=Bulk Inserter MK6
5d-bulk-inserter-07=Bulk Inserter MK7
5d-bulk-inserter-08=Bulk Inserter MK8
5d-bulk-inserter-09=Bulk Inserter MK9
5d-bulk-inserter-10=Bulk Inserter MK10
```
I hope This makes it to the official commit so that other people can enjoy your mods.
Thanks a Million

**Comment by McGuten** [comment]
its fixed now
