### ISSUE TITLE
New Logistic - Incompatibility with Factorissimo 3(After 11/25/2024 update)

### ISSUE THREAD

**Issue by VMSolidus** [McGuten/Factorio5DimMods#109]
Today's updates to https://mods.factorio.com/mod/5dim_logistic caused an incompatibility with Factorissimo 3. Specifically New Logistic no longer works with Factorissimo 3, and disabling it allows the other mod to work just fine. 

![image](https://github.com/user-attachments/assets/6ea073b2-a919-4948-ba66-af61df975e79)

**Comment by McGuten** [comment]
sorry i dont understand the problem, that item isnt from 5Dim mod and 5Dim logistic just add tiers from vanilla items
