### ISSUE TITLE
Conflict with 5dim_energy and Cargo ships but only with Krastorio 2 enabled.

### ISSUE THREAD

**Issue by Glendening** [McGuten/Factorio5DimMods#11]
Error while running setup for entity prototype "or_lamp" (lamp): next_upgrade target (5d-lamp-02) must have the same bounding box.
5dim_energy 1.1.2 and cargo-ships 0.0.57 and Krastorio2 1.0.13
Disable any one of the 3 mods and the game loads fine.

**Comment by McGuten** [comment]
Thanks you for the report!

Add compatibility with cargo ships and krastorio in the core 1.1.4!
