### ISSUE TITLE
Error with 5dim Transport

### ISSUE THREAD

**Issue by CoolFreeze23** [McGuten/Factorio5DimMods#116]
Other mods appear to be working fine. But transport is giving me this error

"Failed to load mods: __5dim_core__/lib/transport/generation-transport-belt.lua:409: attempt to index field 'sheet' (a nil value)
stack traceback:
	__5dim_core__/lib/transport/generation-transport-belt.lua:409: in function 'genTransportBelts'
	__5dim_transport__/prototypes/gen-transport-belt.lua:7: in main chunk
	[C]: in function 'require'
	__5dim_transport__/data.lua:8: in main chunk

Mods to be disabled:
• 5dim_transport (2.0.10)"

**Comment by CoolFreeze23** [comment]
Also want to add that I didnt have transport in my save prior to this. But I had Module and it was fine. After removing Transport and updating Module, I'm getting this error now 

"Failed to load mods: __5dim_core__/lib/module/generation-module.lua:240: attempt to index local 'itemQuality' (a nil value)
stack traceback:
	__5dim_core__/lib/module/generation-module.lua:240: in function 'genModules'
	__5dim_module__/prototypes/gen-modules.lua:8: in main chunk
	[C]: in function 'require'
	__5dim_module__/data.lua:2: in main chunk

Mods to be disabled:
• 5dim_module (2.0.3)"

**Comment by estudiobarragan** [comment]
after the last update, Factorio dont make error to load, but when i load a game, show me a error message:

![image](https://github.com/user-attachments/assets/f1781273-7565-41df-b675-91b429767cf5)

So, dissapear my bulk inserter. Its a mistake ? its on purpose?

**Comment by McGuten** [comment]
rf- items isnt from 5dim mods, probably the mod should update with the changes

**Comment by CoolFreeze23** [comment]
> rf- items isnt from 5dim mods, probably the mod should update with the changes

I'm using the latest version and still getting my error
