### ISSUE TITLE
[Issue][New Battlefield] Turrets not receiving bonus projectile damage

### ISSUE THREAD

**Issue by RobinDatura** [McGuten/Factorio5DimMods#121]
When I research any Physical projectile damage, it doesn't apply its bonus to the turret except for "Turret MK1"

When hovering over the icons in the Technology tree, it shows "Unknown key: 'modifier-description.5d-gun-turret-small-01-attack-bonus'"
![image_2024-12-07_155051785](https://github.com/user-attachments/assets/33200a6c-1146-46d8-a9fd-0e5e84d7c728)
![Screenshot 2024-12-07 155150](https://github.com/user-attachments/assets/71275f45-9442-46ce-b9cf-0a1e04bd7975)
![Screenshot 2024-12-07 155202](https://github.com/user-attachments/assets/d17cbbf8-fa29-45b9-9ef6-31a4fb5c0b91)

**Comment by McGuten** [comment]
resolved
