### ISSUE TITLE
Conditional requrie statements not allowed

### ISSUE THREAD

**Issue by kryojenik** [McGuten/Factorio5DimMods#126]
Conditional 'require' statements are not allowed in Factorio mods because they cause the same mod version to load with a different code hash (different number of source files loaded) depending startup settings. Joining a multiplayer server will fail if the mod hash is wrong, and it will not sync the mod settings automatically when that happens.

Instead, your mod must put the IF statement within the file, so that the file is always included in the Lua state but its contents are only executed when the condition is true. Specifically this one in data-updates will be a problem:

https://github.com/McGuten/Factorio5DimMods/blob/19df123218b2cd2504f4fc26d66f4cc0b039c8ea/5dim_transport/data-updates.lua#L19

See: https://forums.factorio.com/viewtopic.php?f=29&t=102335&p=567589#p567589

**Comment by McGuten** [comment]
Fixes in next update
