### ISSUE TITLE
Steam Turbine blueprint shows unresearched

### ISSUE THREAD

**Issue by dachrissi81** [McGuten/Factorio5DimMods#129]
After updating the 5dim packages i could build the unresearched steam tubines from mk4 up to mk9
![image](https://github.com/user-attachments/assets/ec1ecb1c-9780-4300-a670-703d22985ef4)
![image](https://github.com/user-attachments/assets/ec3beee7-79bd-46c2-a93f-fbcb7d5ab115)

Version update was:
![image](https://github.com/user-attachments/assets/b4e94ff5-4984-40ee-9caa-3f7ce0fba406)

**Comment by McGuten** [comment]
fixed
