### ISSUE TITLE
conflect with boblogistic and bobwarfare

### ISSUE THREAD

**Issue by abdllah197** [McGuten/Factorio5DimMods#14]
it was working on factorio 1.0 , but after updating to factorio 1.1.5 and updating all mods it shows that

![Screenshot (9)](https://user-images.githubusercontent.com/66393459/101804400-376cd580-3b1a-11eb-9a83-7472c9d9c426.png)
![Screenshot (10)](https://user-images.githubusercontent.com/66393459/101804403-38056c00-3b1a-11eb-827e-12710b1d8e07.png)

**Comment by McGuten** [comment]
Thanks you for the report.

Added compatibility in the last update (5Dim's mod - Compatibility) with bob's mod!
