### ISSUE TITLE
[1.0] Entities do not generate pollution

### ISSUE THREAD

**Issue by ttr** [McGuten/Factorio5DimMods#16]
Hi,
Boiler (mk2 at least) for steam generation and Mashers do not generate any pollution.
Can you implement pollution for all buildings/vehicles, based on fuel burn rate or if fuel is not burned directly, based on crafting speed / tech level?

Thank You.

**Comment by McGuten** [comment]
i rewrite all mod in 1.1 version, try this version ;)

**Comment by ttr** [comment]
I've did - broke my save and blueprints but it's fine :)
and i can see pollution is in 1.1.
