### ISSUE TITLE
5 Dim's Mod

### ISSUE THREAD

**Issue by Mhowie6439** [McGuten/Factorio5DimMods#2]
I have been using your mod for a long time now. I like having the bots at the start as well as the jump start I get from your mod. Now that ver1.0 for the game is out your mod is not working in total. I do not have the equipment I use to have let alone any of the bots to use right away. Is there anything I am doing wrong now with the newer vers of  your mod or any new settings I should know about?

**Comment by McGuten** [comment]
fixed, ty for report ^^
