### ISSUE TITLE
Error while loading 5dim_enemies

### ISSUE THREAD

**Issue by Icecoldmeat** [McGuten/Factorio5DimMods#21]
I'm getting the error below when i try to load your mod:

![afbeelding](https://user-images.githubusercontent.com/61988576/104842764-25274980-58c7-11eb-9d9b-f092c6291a45.png)

Am i doing something wrong?

**Comment by McGuten** [comment]
Show me the modlist please.

**Comment by Icecoldmeat** [comment]
Sorry for my late reply didn't see my e-mail in time. Normally i use a bunch of mods, so at first i thought there was a conflict with another mod, however when i turn off every mod except yours i still get the error.

This is the modlist
![afbeelding](https://user-images.githubusercontent.com/61988576/105049423-eb904300-5a6c-11eb-9a5b-06aff7fd4cdd.png)

When i click confirm i will get the error shown in my first post.
