### ISSUE TITLE
Cant change some options like more health to enemies

### ISSUE THREAD

**Issue by Alphanex1** [McGuten/Factorio5DimMods#3]
Hi McGuten

first of all i really love your mods and play factorio since long time with them. Using your newest mod (enemies) aswell and its a nice mod because finally the enemys starting to attack like they should do normaly. But there are some issues in my opinion. First of all i cant change since the patch the hp for the enemys over the mod option menue. The other thing is that all your buildings (Miningdrill for example) dont produce any polution. The basic electric one produce 10 per minute, all following ones dont produce any polution. The mk2 oilpump dont produce any polution aswell. So its really nice to have a mod like enemies which rise the spawnrate from enemys extremly, but what does it bring when all your buildings dont produce any polution to feed them? Would be really awesome if you could fix

**Comment by McGuten** [comment]
Hello!

I'm pretty happy you said that!
The enemies still have some way to go to be refined, but I'm happy with the first throw.

About the options, if you have problems with the enemies' options is probably because you have installed the mod rampant, which is incompatible with these parameters (it gives an error when starting 5Dim with rampant).

About the rest of the problems about the constructions, I am rewriting a big part of the mod to improve it and make it grow (a lot, after the change the mod will have much more content and you will be able to do much bigger things)

I hope that solve you questions and problems.

**Comment by Alphanex1** [comment]
Nice to see that you are one of the few modder who really answer to problems :D

 

Well i tried the rampant mod, but after i saw that its incompatible i deleted it. But the options didnt came back and i still cant change them. I can change the hp i have as player, but not the enemys. 

 

The first launch of the enemy mod is indeed an access. I already had a little farer savegame where my base was save without any problems, after i installed the new mod i couldnt watch fast enough and had at several directions holes in my deffence :D

 

But i really hope you will change the polution of your hole buildings. The best/worst example are boilers for steamengines. The vanilla boiler produce 30 polution per minute, the mk2 from your mod nothing. So you can make the spawn as cheape as you want, if you dont produce any polution due such "problems" there wont be any enemies.

With the current status you can cheate extremly with just building mk2 boiler or mk2 oildrills and so on which doenst produce any polution and you dont trigger any enemeys. Oiloutposts dont need a defence because you dont trigger them, polutionmodules which you modded till level 5 too are completly useless. 


 

Gesendet: Dienstag, 25. August 2020 um 18:38 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

Hello!

I'm pretty happy you said that!
The enemies still have some way to go to be refined, but I'm happy with the first throw.

About the options, if you have problems with the enemies' options is probably because you have installed the mod rampant, which is incompatible with these parameters (it gives an error when starting 5Dim with rampant).

About the rest of the problems about the constructions, I am rewriting a big part of the mod to improve it and make it grow (a lot, after the change the mod will have much more content and you will be able to do much bigger things)

I hope that solve you questions and problems.

**Comment by McGuten** [comment]
I check it, you dont have battlefield installed?

i will add it on enemies too, ty for report ^^

**Comment by McGuten** [comment]
it is updated in new version, please update it a test it to confirm

**Comment by Alphanex1** [comment]
i have battlefield installed^^ Saw the updates but still not enable to change the hp from enemies. 2-3 days ago it was possible, than you updated one of your mods (core or battlefield) and after this update it wasnt possible anymore.

 
 

Gesendet: Dienstag, 25. August 2020 um 19:42 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

it is updated in new version, please update it a test it to confirm

**Comment by McGuten** [comment]
show me your mods installed, please

**Comment by Alphanex1** [comment]
my active modlist

 

 


https://prnt.sc/u5r5rq

 

 

Gesendet: Dienstag, 25. August 2020 um 20:26 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

show me your mods installed, please

**Comment by McGuten** [comment]
and the mod settings list, please?

**Comment by Alphanex1** [comment]
The option was gone bevore you released the enemies mod.

 


https://ibb.co/Df3YHjB

 

thx that you work on it :D

 

Gesendet: Dienstag, 25. August 2020 um 21:46 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

and the mod settings list, please?

**Comment by McGuten** [comment]
I update new version for core, can u test it again?

the problem should be solved

**Comment by Alphanex1** [comment]
Now its working :D

 

Thx for solving the problem.

 

You dont maybe want to give a hint on what you will work the next time at your mods?

 
 

Gesendet: Mittwoch, 26. August 2020 um 08:03 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

I update new version for core, can u test it again?

the problem should be solved

**Comment by McGuten** [comment]
Hello,

I am making all the components of the game have up to tier 10 (for example the electric furnace and mashers that are already finished go from level 1 (vanilla in case of the furnace) now come to electric furnace MK10, with more slots of modules, speed improvements (with appropriate emissions)

My intention is to do this with a large part of the mod to make it grow and improve the experience.

What do you think?

**Comment by Alphanex1** [comment]
Tier 10 sounds crazy especially in the lategame when you reach them. They are awesome for longer taking recipes like electric engine or the science packs. But for things which only take 0.5sec basic craftingtime it will be crazy to supply it with enough recourses :D 

 

Balance will be hard between the mk10 crafting buildings and the assembly line aswell the grip arms without getting cancer in the eyes because they are moving so extremly fast.

 

But with t10 buildings its maybe possible to build really small, but extreme efficient outposts/bases.

 

Beside this i would balance the higher turrets in the battlefield mod. For example the sniper turret deals with low science and without uranammo already 15k damage per hit. With that damage everything dies with 1 shot beside the physical enemies, and they die with 1 shot from the tesla turret. 

 
 

Gesendet: Mittwoch, 26. August 2020 um 11:35 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

Hello,

I am making all the components of the game have up to tier 10 (for example the electric furnace and mashers that are already finished go from level 1 (vanilla in case of the furnace) now come to electric furnace MK10, with more slots of modules, speed improvements (with appropriate emissions)

My intention is to do this with a large part of the mod to make it grow and improve the experience.

What do you think?

**Comment by McGuten** [comment]
Yes, I give you an example in game: 
https://i.gyazo.com/ba331e9223410e4871536f3603c94cd3.png
If you look, the normal pollution of an electric oven is 1, in this case it is 7.75 (much higher, the same as the rest of the parameters)
https://i.gyazo.com/89c0459743fbb58b133f9f0d3d569d1b.png
In the case of the masher it is something similar
This will probably need to be touched up, but I think it's a good place to start.

About the combat part, yes, the battlefield module will be completely modified according to the new changes of the rest of modules, small gun turret will also receive its MK1 to MK10 versions with improvements mainly in range and, obviously in damage
The larger turrets (like snipers or tesla) will be nerfe to low levels especially in the distance section, my idea is that the turrets have these ranges:
for gun turrets
small 20 (these turrets have more attack speed)
medium 25 (these turrets are the standard)
big 30 (these turrets have more range at the expense of speed)
sniper 45 (these turrets have a lot of range with a very low cadence)
This will be applied to MK1 turrets, their MK10 versions will probably have +10 range (I'm not sure of the numbers, maybe 15, 20... who knows) and some more damage.

**Comment by Alphanex1** [comment]
Sounds good. Im sure you will change the energy production aswell right? In my opinion the coalconsume from the steamengines is way to low. Especially that a level 1 and level 3 steamengine consume the same ammount of coal ist little bit inbalance/cheat in my opinion. What do you think about this?

 

Just an idea about the turrets: Instead of making 10 different gun turrets (mk1-10) aswell laserturrets (mk1-10) (thats how i understand it now) why you dont make 3-4 different turrets like they are now where each turret has his good aswell bad thing (sniper for example high range, but low firerate so good to kill the first enemies, but way to low firerate to kill a hole attack) and add the possibility to research higher range like you can do for more damage aswell higher firerate. 

For example: Small 10, Medium 15, Big 20, sniper 30 as basic range, and than +10% range per researchlevel over 10 level that you have in the end 20, 30, 40, 60 range. (60 is far but its a sniper so it should have high range).

 

With this you dont need to overhaul your hole deffence each time when you research a new mk version of a turret. 

 

Beside this the bigger turrets are way too cheape to produce. The sniper only costs 20 iron or so more than the medium turret and especially the same materials. Maybe the turrets should costs circuits aswell. Medium the green, big the red and sniperturrets the blue circuiits for example

 
 

Gesendet: Mittwoch, 26. August 2020 um 12:38 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

Yes, I give you an example in game:
https://i.gyazo.com/ba331e9223410e4871536f3603c94cd3.png
If you look, the normal pollution of an electric oven is 1, in this case it is 7.75 (much higher, the same as the rest of the parameters)
https://i.gyazo.com/89c0459743fbb58b133f9f0d3d569d1b.png
In the case of the masher it is something similar
This will probably need to be touched up, but I think it's a good place to start.

About the combat part, yes, the battlefield module will be completely modified according to the new changes of the rest of modules, small gun turret will also receive its MK1 to MK10 versions with improvements mainly in range and, obviously in damage
The larger turrets (like snipers or tesla) will be nerfe to low levels especially in the distance section, my idea is that the turrets have these ranges:
for gun turrets
small 20 (these turrets have more attack speed)
medium 25 (these turrets are the standard)
big 30 (these turrets have more range at the expense of speed)
sniper 45 (these turrets have a lot of range with a very low cadence)
This will be applied to MK1 turrets, their MK10 versions will probably have +10 range (I'm not sure of the numbers, maybe 15, 20... who knows) and some more damage.

**Comment by McGuten** [comment]
Yes, in the end everything will be reworked from 0 based on the new values that the base game has.
Everything you say about the energy will also be adjusted (like the rest of the constructions)

Making a technology that directly modifies the range of the turrets is not clear to me if it is possible, but I could try, I do not promise anything.

About modifying the defense, the idea I have is about this is to use the update plane, with this the bots can update or modify the defenses without you having too much trouble.

The cost of the turrets will also change by tiers rather than types, the MK10 turrets will use advanced materials, for example low density structures or processing units.
I also plan that the gun turret research will unlock all 3 types of turrets, small, medium and large instead of using 3 different technologies.
The sniper turrets will have their own technology separated by laser and gun.

And the rest will be a little bit on the fly, I don't have too many things decided.
But the battlefield mod will be the one that gets more additions than the rest, I want to try some things to improve the combat of the game.
We'll see what comes out.

**Comment by Alphanex1** [comment]
Sounds good^^ I dont have any knowlege about modding. How long does it take to create/write/change such mods/add new buildings and so?

 

Dont know if something like this possible for factorio: an "aimingbot" or better said that you can tell your turrets what they should focus. For example that you can say the sniperturrets should focus on large enemies while the smaller turrets should focus on small enemies.

 

Really looking forward to see the changes and play them

 
 

Gesendet: Mittwoch, 26. August 2020 um 13:55 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

Yes, in the end everything will be reworked from 0 based on the new values that the base game has.
Everything you say about the energy will also be adjusted (like the rest of the constructions)

Making a technology that directly modifies the range of the turrets is not clear to me if it is possible, but I could try, I do not promise anything.

About modifying the defense, the idea I have is about this is to use the update plane, with this the bots can update or modify the defenses without you having too much trouble.

The cost of the turrets will also change by tiers rather than types, the MK10 turrets will use advanced materials, for example low density structures or processing units.
I also plan that the gun turret research will unlock all 3 types of turrets, small, medium and large instead of using 3 different technologies.
The sniper turrets will have their own technology separated by laser and gun.

And the rest will be a little bit on the fly, I don't have too many things decided.
But the battlefield mod will be the one that gets more additions than the rest, I want to try some things to improve the combat of the game.
We'll see what comes out.

**Comment by McGuten** [comment]
I am not sure how long it will take to make all the changes, there are some that take little time and there are others that take a lot.

Depending on my current job and the amount of free time I have, I think it will be a few weeks or a month or so.

I must also say that all these changes will require a new game, there are many changes and it is hard to do it otherwise.

**Comment by Alphanex1** [comment]
Jeah its clear that it will take a new game and its good so. With all those changes the game will change a lot that its definitifly worth to start another base.


 

Also I was thinking of adding a new form of walls to the game could improve the feeling and gameplay. Currently Walls more likely function as a buyer of time in some sort and get destroyed quite easily and have to be replaced.

What I am thinking of is adding 2 new types of walls that will consume ressources over time adding more strain on the production.

For example thre Tiers of that new kind of wall.

 

A) Renewing Concrete Wall. - A Wall that can be hooked up to tanks or production machine producing concrete ( Stone and Water or so and fillable in tanks) hooked up to the wall will provide a certain amount of healing to the wall after beeing damaged.

 

Second Tier B) Nanite Wall - Renewing Metal Wall. Metal that needs Liquified from Iron to be hooked up to or Construction from Nanites. New Tier higher Healing output.

 

Third Tier C) Plasma / Energy shield Needs to be provided with energy and I was thinkg of maybe adding a certain amount af damage reflection or an add running through the wall being killed but as for every tier more attacks drains the ressources they are provided

 

Maybe you are already thinking about another walls or what to you think about something like this?

 

Really looking forward to see what you will change. If i can help you with testing something ingame let me know

 

Gesendet: Mittwoch, 26. August 2020 um 16:32 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

I am not sure how long it will take to make all the changes, there are some that take little time and there are others that take a lot.

Depending on my current job and the amount of free time I have, I think it will be a few weeks or a month or so.

I must also say that all these changes will require a new game, there are many changes and it is hard to do it otherwise.

**Comment by McGuten** [comment]
You use discord?
Add me and we can talk ^^

**Comment by Alphanex1** [comment]
I only use it to write there with some people but try to avoide any voice there^^ 

Especially when its in english because my english isnt good enough for voice^^

 

Cant add you without your complete Tag. Mine is: Alphanex#7778
 

Gesendet: Mittwoch, 26. August 2020 um 20:16 Uhr
Von: "McGuten" <notifications@github.com>
An: "McGuten/Factorio5DimMods" <Factorio5DimMods@noreply.github.com>
Cc: "Alphanex1" <Andy_W.-Wagner@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [McGuten/Factorio5DimMods] Cant change some options like more health to enemies (#3)


 

You use discord?
Add me and we can talk ^^
