### ISSUE TITLE
5dim_core: attempt to index field "5d-suicide" (a nil value)

### ISSUE THREAD

**Issue by hasezoey** [McGuten/Factorio5DimMods#5]
This error comes since updating all mods to 1.1

![Screenshot from 2020-12-07 11-05-27](https://user-images.githubusercontent.com/10911626/101337591-26069d80-387c-11eb-890a-e6b283bcc736.png)

already tried factorio's "reset mod settings" and manually deleting `mod-settings.dat`

system: Linux Mint 20

**Comment by McGuten** [comment]
fixed in the last version
