### ISSUE TITLE
Laboratories do not accept AAI/Krastorio Basic Tech Cards

### ISSUE THREAD

**Issue by Glendening** [McGuten/Factorio5DimMods#53]
The laboratories added by "5Dim's mod - New Automatization" do not accept AAI/Krastorio Basic Tech Cards. Even with "5Dim's mod - New Compatibility" installed along side. Is there a setting I am missing or are the Basic Tech Cards just not compatible?

**Comment by MaxFirestorm** [comment]
Was about to open a new issue reporting the same. Anything above the most basic lab won't accept Basic Tech Cards from Krastorio 2 at all. There's no slot for them.
