### ISSUE TITLE
Incompatability with Space Exploration

### ISSUE THREAD

**Issue by Waterspark63** [McGuten/Factorio5DimMods#54]
I had gotten a crash with SE and 5dims together, after talking on the SE Discord, I was told that if the beacons were given the ability to be placed in space (se_allow_in_space = true) in the prototype definition, it should resolve itself. If you could do that it would be very much appreciated! 
Crash Image:
![image](https://user-images.githubusercontent.com/23124229/181431163-3f05309a-76ca-4663-8b92-779f43390c41.png)

**Comment by Mernom** [comment]
Either remove the next_upgrade and upgrade group from the vanilla beacon, or give your beacons `se_allow_in_space = true` prototype field.

**Comment by Gasaraki** [comment]
SE+KR2+5Dim. I can't create a new game :(
