### ISSUE TITLE
2 conflicts with AAI Industry

### ISSUE THREAD

**Issue by Glendening** [McGuten/Factorio5DimMods#6]
5dim_equipment 1.1.0 and aai-industry 0.5.3
Error while running setup for recipe prototype "power-armor-mk2" (recipe): Duplicate item ingredients are not allowed (power-armor exists 2 or more times)

5dim_mining 1.1.2 and aai-industry 0.5.3+aai-containers 0.2.6
Error while running setup for entity prototype "offshore-pump" (offshore-pump): next_upgrade target (5d-offshore-pump-02) must have the same bounding box.

**Comment by McGuten** [comment]
Thanks you for the report.

Is fixed and updated in the mod portal

**Comment by francoisdejgr** [comment]
FYI:
Get the same issue on Mining 1.1.3 and aai-industry 0.5.14 (but not using aai-containers
So only using your mods
Thx for the great mods
