### ISSUE TITLE
Recipe for Underground Belt MK1 length 30 and 50 are missing

### ISSUE THREAD

**Issue by Gootzi** [McGuten/Factorio5DimMods#66]
![image](https://user-images.githubusercontent.com/124401935/219958748-4d348ce5-f715-48a6-8b2f-1c910a350825.png)

**Comment by bradzoob** [comment]
Just a calibration post; I've just played it this evening and had no issue with these recipes, fresh computer so fresh install of latest Factorio and only the 5Dim mods that were updated in last 2 weeks. Oh + a black market 2 mod. There does seem to be some double up of recipes though, vanilla accumulators and 5Dim as separate accumulators to research for example, check your research tree again perhaps it's a different path, for reference the vanilla accumulators just looks like the normal factorio graphic but all the 5Dims are yellow for some weird reason they're using saturated/colourized graphics blech :P

**Comment by Gootzi** [comment]
They are shown as unlocked with the first Logistics upgrade

![image](https://user-images.githubusercontent.com/124401935/219988379-e9e526be-8efa-44af-9797-c1cd18ca511d.png)

so it's probably because I started the save without mods, but added the mod later
