### ISSUE TITLE
5dim New Equipment BUG

### ISSUE THREAD

**Issue by sweetNvicious** [McGuten/Factorio5DimMods#68]
When putting in a personal roboport above mk2, it reverts back to a mk2 when placed inside the armor grid

**Comment by mike1172** [comment]
Upvoting this issue before creating a new one. 

Roboports > Mk2 when removed from the armor grid and put back into inventory revert them back to Mk2 roboports. 

Pretty annoying every time you want to upgrade your power armor or roboports.
