### ISSUE TITLE
5DIM inserters modified every blueprint in all of my blueprint books

### ISSUE THREAD

**Issue by vfinn** [McGuten/Factorio5DimMods#71]
I can no longer use my massive collection of blueprint books - because 5DIM converted all of my long inserters to 5d-inserter-3 and my fast inserters.  This is extremely frustrating since I have many hours work converting each book to json, replacing 5dim back to normal inserters to regain my blueprints back. This is the definition of a virus. Not happy !

**Comment by mvadovszki** [comment]
Same Issue, is avoiding this issue possible?
