### ISSUE TITLE
5dim's Pumpjack error

### ISSUE THREAD

**Issue by Mengoo96** [McGuten/Factorio5DimMods#72]
Hi, the pumpjack over lvl 1 (mk2 mk3 ecc.) can't placed on oil with error "the pumpjack can't extract this liquid"

**Comment by grixt** [comment]
I have the same issue. This is most likely due to interaction with Krastorio2 as it have mineral water pumpjack. 
I gues it have to do something with naming.

**Comment by SamusHD19** [comment]
also try 5dim's compatibility fix it's working for me
