### ISSUE TITLE
Heatpipe MK2 and upwards - no information?

### ISSUE THREAD

**Issue by headcase0570** [McGuten/Factorio5DimMods#75]
Hello!
I just started upgrading the vanilla heatpipes to 5DIM New Nuclear heatpipes. I've skipped Mk2 entirely and went straight to Mk3 upgrades allround. 

After a while I noticed that the Mk3 heatpipes don't give off that nice orange glow. Looking at the build menu, nothing is specified with the heatpipe information, sure they cost more resources to make but there's no specifications listed that make MK3 better than MK2, and MK2 better than vanilla. 

What's the use of having several heatpipe tiers if here's no performance gain?

**Comment by ttr** [comment]
Hey,
AFAIK energy transfer over pipe is faster and it loses less energy over distance.
