### ISSUE TITLE
Conflict with 5dim Transport and Krastorio 2

### ISSUE THREAD

**Issue by Glendening** [McGuten/Factorio5DimMods#8]
Error while running setup for entity prototype "stack-filter-inserter" (inserter): next_upgrade target (kr-superior-filter-inserter) must have the same fast_replaceable_group (inserter != filter-inserter).
5dim-transport 1.1.0 and Krastorio2 1.0.13

**Comment by McGuten** [comment]
Thanks you for the report!
It is fixed in Core 1.1.3
Krastorio 2 its compatible with 5Dim.
