### ISSUE TITLE
Conflict with 5dim-mining and Space Exploration

### ISSUE THREAD

**Issue by Glendening** [McGuten/Factorio5DimMods#9]
Error while running setup for entity prototype "offshore-pump" (offshore-pump): next_upgrade target (5d-offshore-pump-02) must have the same bounding box.
5dim_mining 1.1.2 and space-exploration 0.5.19 (SE requires AAI Industries be enabled. I don't know if this is related.)

**Comment by McGuten** [comment]
Thanks you!

It is done since yesterday!
