### ISSUE TITLE
[Battlefield] Wrong technology name

### ISSUE THREAD

**Issue by H4ckerxx44** [McGuten/Factorio5DimMods#98]
https://github.com/McGuten/Factorio5DimMods/blob/1ba1d2aff5a57660705ff39f7773fdcbd3e2ea55/5dim_battlefield/locale/en/locale.cfg#L417

This should be 
```cfg
5d-flamethrower-turrets=Flamethrower turret
```

**Comment by H4ckerxx44** [comment]
As seen here
![grafik](https://github.com/user-attachments/assets/93ebbcc2-2fb5-48c6-9028-8e68d8e16234)

**Comment by McGuten** [comment]
its fixed and updated, thanks you!
